name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    #needs: pylint

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r pyproject.toml

    - name: Set up NVC
    - uses: nickg/setup-nvc-ci@v1
      with:
      version: latest

    - name: Run tests
      run: pytest
